---
ahoyapi: v2

commands:

  # Docker Compose commands
  up:
    usage: Build and start project containers.
    cmd: docker compose up -d "$@"

  down:
    usage: Stop and remove project containers.
    cmd: docker compose down

  build:
    usage: Build project containers.
    cmd: docker compose build "$@"

  restart:
    usage: Restart project containers.
    cmd: docker compose restart

  stop:
    usage: Stop project containers.
    cmd: docker compose stop "$@"

  # Development commands
  watch:
    usage: Use Compose Watch for live development.
    cmd: docker compose watch

  cli:
    usage: Start a shell inside the 'govcms' container.
    cmd: docker compose exec govcms bash

  composer:
    usage: Run Composer commands inside the 'govcms' container.
    cmd: docker compose exec govcms composer "$@"

  rector:
    usage: Analyze code with Rector and review suggested changes inside the 'govcms' container.
    cmd: docker compose exec govcms rector "$@"

  phpunit:
    usage: Run PHPUnit tests inside the 'govcms' container.
    cmd: docker compose exec govcms phpunit "$@"

  drupal-check:
    usage: Check code correctness and deprecation errors inside the 'govcms' container.
    cmd: docker compose exec govcms drupal-check "$@"

  # Cypress commands
  cypress:
    usage: Run Cypress tests.
    cmd: |
      cd cy && npm install
      export CYPRESS_BASE_URL=http://localhost:8888
      npx cypress run "cypress/e2e/*" --env drupalDrushCmdLine="docker compose exec govcms drush %command"

  cr:
    usage: Alias for 'cypress'.
    cmd: ahoy cypress

  co:
    usage: Open a new Cypress testing window.
    cmd: |
      cd cy && npm install
      export CYPRESS_BASE_URL=http://localhost:8888
      npx cypress open --env drupalDrushCmdLine="docker compose exec govcms drush %command"
