services:
  ##########################################
  # traefik: The reverse proxy and load balancer
  ##########################################
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      # - "--entryPoints.websecure.address=:443"
      # - "--entryPoints.websecure.http.tls=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./.docker/config/traefik.yaml:/etc/traefik/traefik.yaml
      - "./data/certs:/certs"
    networks:
      - web
      - internal
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3

  ##########################################
  # mailhog: The mail capture service
  ##########################################
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.govcms.localhost`)"
      - "traefik.http.routers.mailhog-http.entrypoints=web"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      # HTTPS Router
      # - "traefik.http.routers.mailhog-https.rule=Host(`mailhog.govcms.localhost`)"
      # - "traefik.http.routers.mailhog-https.entrypoints=websecure"
      # - "traefik.http.routers.mailhog-https.tls=true"
      # - "traefik.http.routers.mailhog-https.tls.certresolver=myresolver"
    networks:
      - web
      - internal

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-drupal}
      MARIADB_USER: ${MARIADB_USER:-drupal}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-drupal}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  ##########################################
  # cypress: Cypress testing service
  ##########################################
  cypress:
    image: cypress/included
    container_name: cypress
    volumes:
      - ./cy:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - internal
    environment:
      - CYPRESS_baseUrl=http://govcms
    entrypoint: [ "npx", "cypress", "run", "--project", "/e2e", "--spec", "/e2e/cypress/e2e/4-ui/*.cy.js" ]

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mariadb_data

networks:
  web:
  internal: