version: '2.1'

jobs:
  cypress:
    docker:
      - image: 'govcmstesting/ci:8.2-nginx'
    working_directory: /app
    environment:
      GOVCMS_TESTS_VERSION: ""
    steps:
      - run:
          name: Checkout tests
          command: |
            git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run:
          name: Start GovCMS
          command: |
           govcms start
      - checkout:
          path: 'tests'
      - run:
          name: Install Cypress Dependencies
          command: |
            cd tests/cy && npm ci
      - run:
          name: Run Cypress tests
          command: |
            cd tests/cy && npx cypress run
      - store_artifacts:
          path: tests/cy/cypress/videos
      - store_artifacts:
          path: tests/cy/cypress/screenshots

workflows:
  version: 2
  main:
    jobs:
      - cypress
