FROM govcmstesting/ci:8.2-nginx

# Set environment variable
ENV GOVCMS_TESTS_VERSION=""
ENV CI=0

# Run govcms setup command
RUN govcms setup && govcms install

# Copy test-related files
COPY --from=govcms.ops/tests --chown=govcms:govcms /tests /app/tests

WORKDIR /app

# Run govcms start command when the container starts
CMD ["govcms", "start"]