name: GovCMS CI Tests

on:
  push:
    branches: [ "3.x-develop" ]
  pull_request:
    branches: [ "3.x-develop" ]

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      govcms:
        image: govcmsextras/php:8.2-nginx

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_host: govcms
          CYPRESS_port: 80
        with:
          working-directory: cy
