name: GovCMS CI Tests

on:
  push:
    branches: [ "3.x-develop" ]
  pull_request:
    branches: [ "3.x-develop" ]

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      govcms:
        image: govcmsextras/php:8.2-nginx

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wait for server
        run: |
          until curl -sSf http://govcms > /dev/null; do
            echo "Waiting for server to be accessible..."
            sleep 30
          done
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: http://govcms
        with:
          working-directory: cy
