name: GovCMS CI Tests

on:
  push:
    branches: [ "3.x-develop" ]
  pull_request:
    branches: [ "3.x-develop" ]

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest

    container:
      image: govcmstesting/ci:8.2-nginx
      options: --user govcms:govcms
      env:
        GOVCMS_TESTS_VERSION: ""
        COMPOSER_HOME: /home/govcms/.cache/composer
       
    steps:
    - name: Start GovCMS
      run: |
       govcms start

    - uses: actions/checkout@v4
      with:
        path: 'tests'

    - name: Install dependencies
      run: |
        cd tests/cy && npm ci

    - name: Run Cypress tests
      run: |
        cd tests/cy && npx cypress run --env drupalDrushCmdLine="/app/bin/drush --root=/app/web %command"
